apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T10:12:53Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "763"
  uid: 21cece9d-2f3c-44da-95e4-97598de9f0ac
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.9.215
  clusterIPs:
  - 10.102.9.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32638
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
