apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T07:15:19Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "14422"
  uid: 8db0401e-a284-46f1-a683-6ce417ceb12d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.23.137
  clusterIPs:
  - 10.105.23.137
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30917
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
